### ISSUE TITLE
Exception retrieving machine info

### ISSUE THREAD

**Issue by mekenthompson** [rccoleman/lamarzocco#28]
Just started getting this error, I thought it might be due to 2022.2.2 version, I've tried rolling back to 2022.2.1 and 2021.12.10 but still get the same error.

_________________________

This error originated from a custom integration.

Logger: custom_components.lamarzocco.api
Source: custom_components/lamarzocco/api.py:118
Integration: La Marzocco (documentation, issues)
First occurred: 16:09:20 (9 occurrences)
Last logged: 16:13:42

Caught exception: Exception retrieving machine info: Expecting value: line 1 column 1 (char 0)

**Comment by rccoleman** [comment]
Yes, their server appears to be broken right now. I can get the customer info and token, but none of the other endpoints work. Their official app is also broken right now if you try to retrieve the drink stats or update status, for instance.

**Comment by mrvautin** [comment]
I'm getting it too. official app working fine.

**Comment by rccoleman** [comment]
Trust me, their API aren't working properly.

![image](https://user-images.githubusercontent.com/860888/152629938-cd2d1f8d-3e3d-48a0-bae4-c3de4098518e.jpeg)

**Comment by mekenthompson** [comment]
Yep, official app down too.

Interestingly my Chamberlain myQ app/integration too...maybe a cloud outage affecting multiple companies

**Comment by mrvautin** [comment]
The offical app is working for me to turn it on and off but agree the stats are cooked.

**Comment by mekenthompson** [comment]
@mrvautin Maybe on/off working over local vs cloud?

**Comment by rccoleman** [comment]
That's one of the few things that you can do through the cloud. Some other parts of the official app work because the customer info endpoint works and that provides the token for local access. Unfortunately, if the integration doesn't get everything it needs from the cloud it aborts, so that's why it doesn't work at all right now.

**Comment by rccoleman** [comment]
It's working again for me.

**Comment by mekenthompson** [comment]
Yep, all good. LaMaz cloud back up 👍.

Also, thanks @rccoleman for the integration, it was an annoying 24-48 hours having to turn the machine on manually like some kind of peasant 😜.
