### ISSUE TITLE
This repo is still maintained?

### ISSUE THREAD

**Issue by orxelm** [rccoleman/lamarzocco#31]
There's new features with the v2 home app.
Also, they key's on the readme are no longer working for me.

Thanks
@rccoleman

**Comment by rccoleman** [comment]
> This repo is still maintained?

Yes, I've made 3 releases in the last three weeks that support the new firmware & features.  I didn't change any of the credentials and have had no trouble connecting to my machine post-update.

> Thanks for the nice work @rccoleman

Thanks!
