### ISSUE TITLE
Debug value left in release?

### ISSUE THREAD

**Issue by mrvautin** [rccoleman/lamarzocco#38]
Not sure if it's just my implementation but there seems to be a temp debug value left in the release:

![image](https://user-images.githubusercontent.com/299398/210901620-edec1970-9f02-41da-a9a1-bc210bacc4f2.jpeg)

**Comment by rccoleman** [comment]
I don't control what goes there.  On my machine, the current temperature is on the left, and the set temp is on the right:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/860888/210902133-775b89d7-0039-4040-abf3-e9e234d30e23.png">

I know that there were some recent changes to the water heater integration, but I don't know if that's changed as I never look there.

**Comment by rccoleman** [comment]
I never actually look at the more-info or state display like that, but I'm almost certain that it's coming from [here](https://github.com/home-assistant/frontend/commit/dfc461ce0534ef668b2418bfefa20b59f45127ba#diff-c1ad8eea0cd6b8b2b110a7516c733f9b008139e4a14a7169adb9eb39c066fb70).  The actual output is actually generated [here](https://github.com/home-assistant/frontend/blob/dev/src/components/ha-water_heater-state.js), but that only changed to support the state localization changes to ComputeStateDisplay.

**Comment by rccoleman** [comment]
BTW, I filed https://github.com/home-assistant/frontend/issues/15066 for it.  Let's see what happens, but it looks like it's been that way since at least 2018 based on the git history.

**Comment by rccoleman** [comment]
Turns out it is my fault, based on an intentional decision to publish the current temperature as the state rather than the ones mentioned in the docs that don't have a useful meaning here.  I guess I can just make it "STATE_ELECTRIC" 🤷 .  I think that has implications for the cards that I'm using in the frontend, though.

**Comment by rccoleman** [comment]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/860888/211623598-a30c61b7-4239-4bf7-8db8-36971482a982.png">

It doesn't work work with a hard I'm using, but I guess I can "fix" it, too.

**Comment by rccoleman** [comment]
Released v0.9.7 to add better debug logging and fix the `water_heater` entity state.

**Comment by mrvautin** [comment]
Thanks for looking at it. It makes more sense now and turned out to be far more complex than I thought! I was thinking/hoping it was just a debug value!

**Comment by rccoleman** [comment]
As with many issues, it was a super-simple change in the code.
