### ISSUE TITLE
Is there a way to separate the true amount of cups from the amount of flushes?

### ISSUE THREAD

**Issue by Lxxrxns** [rccoleman/lamarzocco#39]
The total_drinks sensor returns drinks+flushes, but in the native marzocco app you can see stats for both flushes and real cups of coffee.

Right now I have a helper that halves the amount of total_drinks because I normally flush after every cup, but this is suboptimal.

**Comment by Lxxrxns** [comment]
Wow, OK, I had no idea there were several subvalues/attributes to this total_drinks entity. Any chance you could explain how to access these attributes in Home Assistant, for example in an automation?

![Screenshot_20230117_185903_Home Assistant](https://user-images.githubusercontent.com/12428228/212976364-3d4d4839-5bf2-4000-9850-5adc4fdddb91.jpg)

**Comment by rccoleman** [comment]
How to access and use attributes is basic HA functionality, so assuming the information you want is present, I'm going to close this issue.  If the numbers are incorrect, please file a new issue.
