### ISSUE TITLE
"Front Panel Display" Attribute missing first character

### ISSUE THREAD

**Issue by ari-za** [rccoleman/lamarzocco#41]
Hi

I've noticed a while ago however the “Front panel display” attribute on the Coffee Machine entity is missing the first character. It used to work but after one of the updates (integration or machine cant remember) it got messed up. More likely the machine update.

Thanks!

<img width="546" alt="Screenshot 2023-03-16 at 16 01 45" src="https://user-images.githubusercontent.com/8730066/225670305-1b50d555-447f-44b9-a392-ff765b18d1a7.png">

**Comment by rccoleman** [comment]
They must have moved some stuff in the latest machine update, which you're currently missing (see the "Yes" in your screenshot).  When I updated to v1.40, I had a garbage character in the first position and adjusted that field to "fix" it without having a machine using older firmware to check the behavior.  I don't really want to sprinkle the code with "if version x, do this, else do this" logic, especially for cosmetic stuff like this, so I suggest updating to the latest firmware version.  The temperature readout is probably also wrong now and will be correct when you update the machine firmware.

Here are my attributes with the latest firmware:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/860888/225694372-702fe6d5-10d6-4af4-88f8-07598ecb85a7.png">

**Comment by ari-za** [comment]
Thanks, it’s not showing an update in my LM app so I need to investigate why this is. Perhaps I will mail them since they are known to remotely apply updates too. Will feedback

**Comment by rccoleman** [comment]
I suppose there could be. The firmware versions for the Linea Mini are completely different, but the integration otherwise works fine on them.  [This](https://home.lamarzoccousa.com/la-marzocco-home-app-v-2/) is their blog post and I don't see a distinction between AV and MP. 

> Linea Minis with serial numbers starting with LM015906 and GS3s starting with serial number GS012984 come standard with the new connected board.

[Here's](https://www.home-barista.com/espresso-machines/la-marzocco-home-v2-requires-firmware-update-t83118.html#p888922) someone who updated their GS3 MP.

In any case, I don't want to start changing behavior for different versions that I don't have access to, especially for cosmetic things like this.

**Comment by ari-za** [comment]
In that blog post they updated from 1.22 to 1.23. So v1.23 is the latest for the MP.

I figured anyone else with an MP on v1.23 will have the same experience. Maybe they could chime in. 

Not that important I guess but would benefit the whole MP user base assuming everyone has the same issue and it’s not a weird issue with mine only. 

My serial is GS0151xxx so it had the connected board from the factory. 

Let me know if you wanted me to log anything to help fix this. 

Thanks

**Comment by rccoleman** [comment]
I really don't know why they made this weird change, but it looks like the front panel display text was just shifted right by one byte, leaving a leading null.  It's easy enough just to switch back to the original starting address and strip nulls, so I'll do that in an update.

**Comment by rccoleman** [comment]
I'm archiving this repo because this integration no longer works with current machine firmware. Please move to https://github.com/zweckj/lamarzocco.
