### ISSUE TITLE
Drinks Count Not Updating

### ISSUE THREAD

**Issue by aspen33619** [rccoleman/lamarzocco#45]
Hi,
thanks for the great integration, we are really enjoying it!!

In out HA, the drinks counter only updates on a restart of HA. Since nobody but me has complained about this, I assume doing something wrong. Can you help me?

Thanks for your time.

**Comment by zweckj** [comment]
are you on the old or the new Gateway version?

**Comment by rccoleman** [comment]
I'm archiving this repo because this integration no longer works with current machine firmware.  Please move to https://github.com/zweckj/lamarzocco.
