### ISSUE TITLE
Struggling to install beta

### ISSUE THREAD

**Issue by TransientWolf** [rccoleman/lamarzocco#47]
Trying to install beta to fix after LM firmware upgrade broke the connection.  Still learning HA.  Cannot install via HACS as only allows the previous 0.9.6 to be installed.  If i download the source code and try to install manually and copy all the files in the lamarzocco folder to custom config it doesnt find my machine automatically so i go to add the integration and it wants me to add 5 lines of data which i assume is the client id secret id etc etc.  But it has no identification tags for each line so no idea what to fill where.  the second and 4th lines have show/hide icons.  Any help appreciated.

**Comment by rccoleman** [comment]
You should uninstall my repo and add this one via the 3-dot menu: https://github.com/zweckj/lamarzocco.  Then install it via the Integrations section

**Comment by TransientWolf** [comment]
Hi  Thanks so much - I did not know about the 3-dot menu to load a custom repository  D'oh  All working.
